# Generated by Django 4.1.7 on 2023-04-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_user', models.PositiveIntegerField()),
                ('max_active', models.PositiveIntegerField()),
            ],
        ),
    ]
