# Generated by Django 4.1.7 on 2023-03-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoLi', '0002_completedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='ctuser',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='tuser',
            field=models.IntegerField(default=55),
            preserve_default=False,
        ),
    ]
